# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fauxgartic_pb2 as fauxgartic__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fauxgartic_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FauxGarticServiceStub(object):
    """MUDANÇA: Nome do serviço atualizado para FauxGarticService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EntrarNoJogo = channel.unary_unary(
                '/FauxGarticService/EntrarNoJogo',
                request_serializer=fauxgartic__pb2.Jogador.SerializeToString,
                response_deserializer=fauxgartic__pb2.EstadoDoJogo.FromString,
                _registered_method=True)
        self.ReceberEventos = channel.unary_stream(
                '/FauxGarticService/ReceberEventos',
                request_serializer=fauxgartic__pb2.Jogador.SerializeToString,
                response_deserializer=fauxgartic__pb2.EventoDeJogo.FromString,
                _registered_method=True)
        self.EnviarAcao = channel.unary_unary(
                '/FauxGarticService/EnviarAcao',
                request_serializer=fauxgartic__pb2.AcaoJogador.SerializeToString,
                response_deserializer=fauxgartic__pb2.Vazio.FromString,
                _registered_method=True)


class FauxGarticServiceServicer(object):
    """MUDANÇA: Nome do serviço atualizado para FauxGarticService
    """

    def EntrarNoJogo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceberEventos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarAcao(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FauxGarticServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EntrarNoJogo': grpc.unary_unary_rpc_method_handler(
                    servicer.EntrarNoJogo,
                    request_deserializer=fauxgartic__pb2.Jogador.FromString,
                    response_serializer=fauxgartic__pb2.EstadoDoJogo.SerializeToString,
            ),
            'ReceberEventos': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceberEventos,
                    request_deserializer=fauxgartic__pb2.Jogador.FromString,
                    response_serializer=fauxgartic__pb2.EventoDeJogo.SerializeToString,
            ),
            'EnviarAcao': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarAcao,
                    request_deserializer=fauxgartic__pb2.AcaoJogador.FromString,
                    response_serializer=fauxgartic__pb2.Vazio.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FauxGarticService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FauxGarticService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FauxGarticService(object):
    """MUDANÇA: Nome do serviço atualizado para FauxGarticService
    """

    @staticmethod
    def EntrarNoJogo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FauxGarticService/EntrarNoJogo',
            fauxgartic__pb2.Jogador.SerializeToString,
            fauxgartic__pb2.EstadoDoJogo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceberEventos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/FauxGarticService/ReceberEventos',
            fauxgartic__pb2.Jogador.SerializeToString,
            fauxgartic__pb2.EventoDeJogo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarAcao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FauxGarticService/EnviarAcao',
            fauxgartic__pb2.AcaoJogador.SerializeToString,
            fauxgartic__pb2.Vazio.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
