# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fauxgartic.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fauxgartic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66\x61uxgartic.proto\"#\n\x07Jogador\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\"Y\n\x0c\x45stadoDoJogo\x12\x18\n\x10sou_o_desenhista\x18\x01 \x01(\x08\x12\x18\n\x10\x64\x65senhista_atual\x18\x02 \x01(\t\x12\x15\n\rpalavra_atual\x18\x03 \x01(\t\"s\n\x0b\x41\x63\x61oJogador\x12\x19\n\x07jogador\x18\x01 \x01(\x0b\x32\x08.Jogador\x12\x17\n\x05traco\x18\x02 \x01(\x0b\x32\x06.TracoH\x00\x12\x11\n\x07palpite\x18\x03 \x01(\tH\x00\x12\x15\n\x0blimpar_tela\x18\x04 \x01(\x08H\x00\x42\x06\n\x04\x61\x63\x61o\">\n\x05Traco\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\x0b\n\x03\x63or\x18\x03 \x01(\t\x12\x12\n\nnovo_traco\x18\x04 \x01(\x08\"\x86\x01\n\x0c\x45ventoDeJogo\x12\x19\n\x07\x64\x65senho\x18\x01 \x01(\x0b\x32\x06.TracoH\x00\x12\x17\n\rmensagem_chat\x18\x02 \x01(\tH\x00\x12!\n\x0emudanca_rodada\x18\x03 \x01(\x0b\x32\x07.RodadaH\x00\x12\x15\n\x0blimpar_tela\x18\x04 \x01(\x08H\x00\x42\x08\n\x06\x65vento\":\n\x06Rodada\x12\x17\n\x0fnome_desenhista\x18\x01 \x01(\t\x12\x17\n\x0fpalavra_secreta\x18\x02 \x01(\t\"\x07\n\x05Vazio2\x8d\x01\n\x11\x46\x61uxGarticService\x12\'\n\x0c\x45ntrarNoJogo\x12\x08.Jogador\x1a\r.EstadoDoJogo\x12+\n\x0eReceberEventos\x12\x08.Jogador\x1a\r.EventoDeJogo0\x01\x12\"\n\nEnviarAcao\x12\x0c.AcaoJogador\x1a\x06.VazioB\x17\n\x13org.fauxgartic.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fauxgartic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023org.fauxgartic.grpcP\001'
  _globals['_JOGADOR']._serialized_start=20
  _globals['_JOGADOR']._serialized_end=55
  _globals['_ESTADODOJOGO']._serialized_start=57
  _globals['_ESTADODOJOGO']._serialized_end=146
  _globals['_ACAOJOGADOR']._serialized_start=148
  _globals['_ACAOJOGADOR']._serialized_end=263
  _globals['_TRACO']._serialized_start=265
  _globals['_TRACO']._serialized_end=327
  _globals['_EVENTODEJOGO']._serialized_start=330
  _globals['_EVENTODEJOGO']._serialized_end=464
  _globals['_RODADA']._serialized_start=466
  _globals['_RODADA']._serialized_end=524
  _globals['_VAZIO']._serialized_start=526
  _globals['_VAZIO']._serialized_end=533
  _globals['_FAUXGARTICSERVICE']._serialized_start=536
  _globals['_FAUXGARTICSERVICE']._serialized_end=677
# @@protoc_insertion_point(module_scope)
